// Generated by CoffeeScript 1.6.2
(function() {
  var proxy;

  proxy = function(fn, context) {
    var p;

    p = function() {
      return fn.apply(context);
    };
    return p;
  };

  if (!String.prototype.format) {
    String.prototype.format = function() {
      var args;

      args = arguments;
      return this.replace(/{(\d+)}/g, function(match, number) {
        if (typeof args[number] !== 'undefined') {
          return args[number];
        } else {
          return match;
        }
      });
    };
  }

  window.Counter = (function() {
    var run;

    Counter.prototype.timer = function() {};

    run = function() {
      var days, diff, hours, mins, now, secs, tuesdays;

      now = new Date();
      diff = Math.abs(this.date - now);
      days = Math.floor(diff / 8.64e7);
      hours = Math.floor((diff % 8.64e7) / 36e5);
      mins = Math.floor((diff % 36e5) / 6e4);
      secs = Math.floor((diff % 6e4) / 1000);
      tuesdays = Math.floor(diff / 6.048e8);
      tuesdays = now.getDay() < 2 ? tuesdays + 1 : tuesdays;
      return this.node.innerHTML = this.fmt.format(days, hours, mins, secs, tuesdays);
    };

    function Counter(datestr, node, fmt, interval) {
      this.node = node;
      this.fmt = fmt;
      this.interval = interval;
      this.date = new Date(datestr);
    }

    Counter.prototype.start = function() {
      proxy(run, this)();
      clearInterval(this.timer);
      return this.timer(setInterval(proxy(run, this), this.interval * 1000));
    };

    Counter.prototype.stop = function() {
      return clearInterval(this.timer);
    };

    return Counter;

  })();

}).call(this);
